### ISSUE TITLE
Very good sample

### ISSUE THREAD

**Issue by MS-ELEX** [dangvanthanh/vue-shopping-cart#1]
Your code is easy to understand and helpful.
However, it can be a one-point concern.
When clicking on the category 'Baby' and later menus , browser freeze.
Probably because there is no product , 'backend' becomes unresponsive.
 If it is a simple problem, please fix it.

**Comment by dangvanthanh** [comment]
Hi @MS-ELEX 

Thank you very much for the feedback. I will fix it soon
