### ISSUE TITLE
Deno and package.json dependencies

### ISSUE THREAD

**Issue by losintikfos** [dangvanthanh/vue-shopping-cart#5]
How do I install the dependencies in `package.json` without using `pnpm` I noticed deno do not support `node_modules`?

Thanks

**Comment by dangvanthanh** [comment]
Hi @losintikfos 

You can use `npm` to install dependencies.

```
$ npm install
```

Almost packages in `package.json`, I use for the client. In the server with Deno, I didn't use dependencies in `package.json`

I can `import` the package in Deno with https://deno.land/ such as:

```javascript
export { Client, Users } from 'https://deno.land/x/appwrite@0.0.2/mod.ts';
```

or CDN such as [Skypack](https://www.skypack.dev/):

```javascript
import appwrite from 'https://cdn.skypack.dev/appwrite';
```
